server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/userservice?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

      