server:
  port: 8083
  
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ratingservice?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka     